//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"0,ENABLED,300,2000,0,0,0,1048575;
1,DISABLED,300,2000,0,4,4,1048575;
2,DISABLED,300,2000,0,8,8,1048575;
3,DISABLED,300,2000,0,12,12,1048575;
4,DISABLED,300,2000,0,1,1,1048575;
5,DISABLED,300,2000,0,5,5,1048575;
6,DISABLED,300,2000,0,9,9,1048575;
7,DISABLED,300,2000,0,13,13,1048575;
8,DISABLED,300,2000,0,2,2,1048575;
9,DISABLED,300,2000,0,6,6,1048575;
10,DISABLED,300,2000,0,10,10,1048575;
11,DISABLED,300,2000,0,14,14,1048575;
12,DISABLED,300,2000,0,3,3,1048575;
13,DISABLED,300,2000,0,7,7,1048575;
14,DISABLED,300,2000,0,11,11,1048575;
15,DISABLED,300,2000,0,15,15,1048575;")]
        public string DefaultAntennaSettings {
            get {
                return ((string)(this["DefaultAntennaSettings"]));
            }
        }
    }
}
